name: x-tint.ai
favicon: null
layout_spectrum: 0.6457767731044441
typography_spectrum: 0.25166159006766975
title: Window Tinting in Kansas City
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060807'
    - '#f9fff5'
    - '#998b82'
    - '#cfbcae'
    - '#403e41'
  brandStrength: 0
  lightness: 0.059627145528793335
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
