name: x-tint.ai
favicon: null
layout_spectrum: 0.6457767731044441
typography_spectrum: 0.25166159006766975
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.390188712393865
  lightness: 0.059627145528793335
  saturation: 0.9854326450731605
  rhythmicContrast: 0.28064419771544635
purpose: []
